### ISSUE TITLE
error in the complex MD

### ISSUE THREAD

**Issue by mrinal-shekhar** [tdudgeon/simple-simulate-complex#2]
Hello tdudgeon
I was trying to follow your protocol for the OpenMM complex simulation. I downloaded your files and simpy ran 
python simulateComplex.py
However i get the following error
ValueError: operands could not be broadcast together with shapes (0,) (21,) 
Please let me know if you had a similar problem
I am attaching a screen shot of my terminal
Mrinal
![OpenMM_error](https://user-images.githubusercontent.com/40069534/89116082-fecb3a00-d45d-11ea-8c7c-e49e0fde201d.png)

**Comment by tdudgeon** [comment]
This is running fine for me. I suspect it's a problem with versions. Are you using the conda environment that is defined in the environment.yml file?
