### ISSUE TITLE
Protein moves out of the water box

### ISSUE THREAD

**Issue by Bio-tx** [tdudgeon/simple-simulate-complex#3]
I performed all steps in this example and it worked pretty well, but when I visualized the output trajectory I found the protien escaped out of the solvation box. 

How to force the protein not to do that? 
thanks a lot

**Comment by tdudgeon** [comment]
Not sure really. I suppose this is very dependent on the system you are modelling.
Is the box big enough - is there enough padding around the protein?

**Comment by Bio-tx** [comment]
I just used the protein files and python codes in the example.

**Comment by jovhuffe** [comment]
Hi, @tdudgeon 
What version of python and anaconda did you run/install the packages in? Also on wat operating system did you code this?
I'm following your example but having a problem installing 'openmmforcefields' on my windows 10 PC (see issue: https://github.com/openmm/openmmforcefields/issues/157)

**Comment by tdudgeon** [comment]
@jovhuffe see the environment.yml file at the top level of the repo.
Running on ubuntu. I wish you luck with windoze!

**Comment by jovhuffe** [comment]
@tdudgeon 
I'm rather new to all this, but definitely switching to linux based systems now :D
