### ISSUE TITLE
Questions about time?

### ISSUE THREAD

**Issue by syedzayyan** [tdudgeon/simple-simulate-complex#5]
Hello @tdudgeon!

Thank you very much for this repo! It has helped me immensely troubleshoot openmm problems. I had a few (stupid) questions.

1. I had a question about the time steps. So how much does 1-time step equate to? Is it 2 femtoseconds?
2. [I did a 10ns (5000000) scale](https://www.kaggle.com/code/syedzayyanmasud/ad1r-6d9h-adn-md?scriptVersionId=138764978) but the ligand stays in the binding pocket. If I were to track the ligand unbinding, would I need to essentially just run it for longer?
3. If I were to simulate an unknown ligand, would I have to use a docked structure or just place the ligand somewhere in the vicinity of the endogenous (co-crystallised) ligand?
4. For protein-protein interactions. Is it a similar script, or does it change? I do understand that the rdkit parts are not required, so I am guessing it's much simpler.

If you can answer any of my questions I would be really grateful. Thanks for reading!

**Comment by tdudgeon** [comment]
Sorry for the delay in responding.
BTW, I'm no expert on the internals of OpenMM so treat anything I say with a bit of caution.

1. this is determined by the parameters give to the [LangevinIntegrator](https://docs.openmm.org/latest/api-python/generated/openmm.openmm.LangevinIntegrator.html). e.g. see https://github.com/tdudgeon/simple-simulate-complex/blob/master/simulateComplex.py#L87C67-L87C91 where it does appear to be 2fs
2. Yes, 10ns isn't very long to observe a ligand unbinding event. And a stable ligand might never unbind. Raising the temperature might make if more likely to unbind.
3. You'd want to start with a fairly stable structure so I would suggest to use docking.
4. I don't have any experience with that, but I suspect you are right.

I haven't looked at these scripts for some time and should probably try to keep them more up to date.
If you have any suggestions or want to make contributions they would be gratefully received!
